# Change these first
owner: brback-app # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: brback-com
    url: https://brback.com
    type: globalping
    location: World
  - name: brback-blog
    url: https://brback.blog
    type: globalping
    location: World

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: brback.info
  # baseUrl: /your-repo-name
  logoUrl: https://www.brback.com/assets/logo.svg
  name: BRBack
  introTitle: "BRBack Status"
  introMessage: "Real-time uptime and incident reports for BRBack services."
  navbar:
    - title: Status
      href: /
    - title: Home
      href: https://brback.com
    - title: Blog
      href: https://brback.blog

  # Internationalized footer (example: only our single copyright line)
  i18n:
    en:
      footer:
        copyright: "© 2025 BRBack"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
